//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0 using the following command:
// xscgen -o ../Models .\AddressValidationResponse.xsd .\AddressValidationRequest.xsd
namespace Pack
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackCollection", Namespace="http://integration.deposco.com/pack")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("packs", Namespace="http://integration.deposco.com/pack")]
    public partial class PackCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackType> _pack;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PackType> Pack
        {
            get
            {
                return _pack;
            }
            private set
            {
                _pack = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackCollection" /> class.</para>
        /// </summary>
        public PackCollection()
        {
            this._pack = new System.Collections.ObjectModel.Collection<PackType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackType", Namespace="http://integration.deposco.com/pack")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Quantity { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("weight", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Weight { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Weight property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WeightSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("weightUOM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WeightUom { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BoxTypeType> _boxTypes;
        
        [System.Xml.Serialization.XmlArrayAttribute("boxTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("boxType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<BoxTypeType> BoxTypes
        {
            get
            {
                return _boxTypes;
            }
            private set
            {
                _boxTypes = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the BoxTypes collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxTypesSpecified
        {
            get
            {
                return (this.BoxTypes.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PackType" /> class.</para>
        /// </summary>
        public PackType()
        {
            this._boxTypes = new System.Collections.ObjectModel.Collection<BoxTypeType>();
            this._customMappings = new System.Collections.ObjectModel.Collection<Types.CustomMapType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dimension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Types.DimensionType Dimension { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("upcs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Upc.UpcCollection Upcs { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("newPackFlag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool NewPackFlag { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NewPackFlag property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NewPackFlagSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lpnTrackingEnabled", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool LpnTrackingEnabled { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the LpnTrackingEnabled property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LpnTrackingEnabledSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("readyToShip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ReadyToShip { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ReadyToShip property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReadyToShipSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.CustomMapType> _customMappings;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("customMappings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customMapping", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.CustomMapType> CustomMappings
        {
            get
            {
                return _customMappings;
            }
            private set
            {
                _customMappings = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("cartonGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CartonGroup { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("preferredCartonType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PreferredCartonType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BoxTypeCollection", Namespace="http://integration.deposco.com/pack")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxTypeCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BoxTypeType> _boxType;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("boxType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<BoxTypeType> BoxType
        {
            get
            {
                return _boxType;
            }
            private set
            {
                _boxType = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="BoxTypeCollection" /> class.</para>
        /// </summary>
        public BoxTypeCollection()
        {
            this._boxType = new System.Collections.ObjectModel.Collection<BoxTypeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BoxTypeType", Namespace="http://integration.deposco.com/pack")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxTypeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Quantity { get; set; }
    }
}
