//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0 using the following command:
// xscgen -o ../Models .\AddressValidationResponse.xsd .\AddressValidationRequest.xsd
namespace Types
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DimensionType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DimensionType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("length", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Length { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Length property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LengthSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("width", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Width { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Width property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WidthSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("height", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Height { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Height property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HeightSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("volume", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Volume { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Volume property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VolumeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("volumeUOM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VolumeUom { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _units = "Inch";
        
        [System.ComponentModel.DefaultValueAttribute("Inch")]
        [System.Xml.Serialization.XmlElementAttribute("units", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Units
        {
            get
            {
                return _units;
            }
            set
            {
                _units = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CustomMapCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomMapCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CustomMapType> _customMapping;
        
        [System.Xml.Serialization.XmlElementAttribute("customMapping", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CustomMapType> CustomMapping
        {
            get
            {
                return _customMapping;
            }
            private set
            {
                _customMapping = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CustomMapping collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomMappingSpecified
        {
            get
            {
                return (this.CustomMapping.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CustomMapCollection" /> class.</para>
        /// </summary>
        public CustomMapCollection()
        {
            this._customMapping = new System.Collections.ObjectModel.Collection<CustomMapType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CustomMapType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomMapType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LengthUnitsType", Namespace="http://integration.deposco.com/types")]
    public enum LengthUnitsType
    {
        
        Inch,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("WeightUnitsType", Namespace="http://integration.deposco.com/types")]
    public enum WeightUnitsType
    {
        
        Pound,
        
        Kilogram,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("WeightType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WeightType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("weight", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double Weight { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _units = "Pound";
        
        [System.ComponentModel.DefaultValueAttribute("Pound")]
        [System.Xml.Serialization.XmlElementAttribute("units", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Units
        {
            get
            {
                return _units;
            }
            set
            {
                _units = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CustomFieldType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomFieldType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private CustomFieldTypeType _type = Types.CustomFieldTypeType.String;
        
        [System.ComponentModel.DefaultValueAttribute(Types.CustomFieldTypeType.String)]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CustomFieldTypeType Type
        {
            get
            {
                return _type;
            }
            set
            {
                _type = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CustomFieldTypeType", Namespace="http://integration.deposco.com/types", AnonymousType=true)]
    public enum CustomFieldTypeType
    {
        
        Integer,
        
        String,
        
        Double,
        
        Boolean,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CarrierSpecialServiceType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarrierSpecialServiceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("shipVendor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipVendor { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saturdayDelivery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool SaturdayDelivery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SaturdayDelivery property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaturdayDeliverySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("saturdayPickup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool SaturdayPickup { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SaturdayPickup property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaturdayPickupSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("insideDelivery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool InsideDelivery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the InsideDelivery property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InsideDeliverySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("pharmacyDelivery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool PharmacyDelivery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PharmacyDelivery property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PharmacyDeliverySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("printReturnLabel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool PrintReturnLabel { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PrintReturnLabel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrintReturnLabelSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("brokerSelectOption", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool BrokerSelectOption { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BrokerSelectOption property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BrokerSelectOptionSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("battery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Battery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Battery property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatterySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("liftgateDelivery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool LiftgateDelivery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the LiftgateDelivery property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LiftgateDeliverySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("returnReceiptRequested", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ReturnReceiptRequested { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ReturnReceiptRequested property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReturnReceiptRequestedSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("notificationPriorToDelivery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool NotificationPriorToDelivery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the NotificationPriorToDelivery property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotificationPriorToDeliverySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("batteryMaterial", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarrierSpecialServiceTypeBatteryMaterial BatteryMaterial { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BatteryMaterial property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatteryMaterialSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("batteryPackaging", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarrierSpecialServiceTypeBatteryPackaging BatteryPackaging { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BatteryPackaging property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatteryPackagingSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("batteryRegulation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BatteryRegulation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("freightBookingConfirmationNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FreightBookingConfirmationNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportComplianceStatement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExportComplianceStatement { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("deliverySignatureOption", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarrierSpecialServiceTypeDeliverySignatureOption DeliverySignatureOption { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the DeliverySignatureOption property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliverySignatureOptionSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("homeDeliveryOption", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CarrierSpecialServiceTypeHomeDeliveryOption HomeDeliveryOption { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the HomeDeliveryOption property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HomeDeliveryOptionSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("collectOnDelivery", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CollectOnDelivery { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CollectOnDelivery property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CollectOnDeliverySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("codCollectionType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodCollectionType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("codTinType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CodTinType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dropOffType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DropOffType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("packagingType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackagingType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("holdAtLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool HoldAtLocation { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the HoldAtLocation property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HoldAtLocationSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fedexOneRate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool FedexOneRate { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the FedexOneRate property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FedexOneRateSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("hazardClass", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double HazardClass { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the HazardClass property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HazardClassSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("properShippingName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProperShippingName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("packingInstructions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackingInstructions { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("cargoAircraftOnly", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CargoAircraftOnly { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the CargoAircraftOnly property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CargoAircraftOnlySpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dangerousGoodsUOM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DangerousGoodsUom { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shipsWithDryIce", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ShipsWithDryIce { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ShipsWithDryIce property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipsWithDryIceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("dutiesPaidByAccount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DutiesPaidByAccount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("unNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UnNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("hazmatLimitedQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HazmatLimitedQuantity { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("limitedQtyPackingInstructions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LimitedQtyPackingInstructions { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("hazmatExceptedQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HazmatExceptedQuantity { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("technicalName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TechnicalName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("alcohol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Alcohol { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Alcohol property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AlcoholSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("medicalUse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool MedicalUse { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the MedicalUse property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MedicalUseSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CarrierSpecialServiceTypeBatteryMaterial", Namespace="http://integration.deposco.com/types", AnonymousType=true)]
    public enum CarrierSpecialServiceTypeBatteryMaterial
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("LITHIUM_ION")]
        LithiumIon,
        
        [System.Xml.Serialization.XmlEnumAttribute("LITHIUM_METAL")]
        LithiumMetal,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CarrierSpecialServiceTypeBatteryPackaging", Namespace="http://integration.deposco.com/types", AnonymousType=true)]
    public enum CarrierSpecialServiceTypeBatteryPackaging
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("PACKED_WITH_EQUIPMENT")]
        PackedWithEquipment,
        
        [System.Xml.Serialization.XmlEnumAttribute("CONTAINED_IN_EQUIPMENT")]
        ContainedInEquipment,
        
        [System.Xml.Serialization.XmlEnumAttribute("STANDALONE")]
        Standalone,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CarrierSpecialServiceTypeDeliverySignatureOption", Namespace="http://integration.deposco.com/types", AnonymousType=true)]
    public enum CarrierSpecialServiceTypeDeliverySignatureOption
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("NONE")]
        None,
        
        [System.Xml.Serialization.XmlEnumAttribute("INDIRECT_SIGNATURE_REQUIRED")]
        IndirectSignatureRequired,
        
        [System.Xml.Serialization.XmlEnumAttribute("DIRECT_SIGNATURE_REQUIRED")]
        DirectSignatureRequired,
        
        [System.Xml.Serialization.XmlEnumAttribute("ADULT_SIGNATURE_REQUIRED")]
        AdultSignatureRequired,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CarrierSpecialServiceTypeHomeDeliveryOption", Namespace="http://integration.deposco.com/types", AnonymousType=true)]
    public enum CarrierSpecialServiceTypeHomeDeliveryOption
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("FEDEX_DATE_CERTAIN_HOME_DELIVERY")]
        FedexDateCertainHomeDelivery,
        
        [System.Xml.Serialization.XmlEnumAttribute("FEDEX_EVENING_HOME_DELIVERY")]
        FedexEveningHomeDelivery,
        
        [System.Xml.Serialization.XmlEnumAttribute("FEDEX_APPOINTMENT_HOME_DELIVERY")]
        FedexAppointmentHomeDelivery,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CustomFieldCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomFieldCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CustomFieldType> _customField;
        
        [System.Xml.Serialization.XmlElementAttribute("customField", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CustomFieldType> CustomField
        {
            get
            {
                return _customField;
            }
            private set
            {
                _customField = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CustomField collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomFieldSpecified
        {
            get
            {
                return (this.CustomField.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CustomFieldCollection" /> class.</para>
        /// </summary>
        public CustomFieldCollection()
        {
            this._customField = new System.Collections.ObjectModel.Collection<CustomFieldType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CarrierSpecialServiceCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CarrierSpecialServiceCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CarrierSpecialServiceType> _carrierSpecialService;
        
        [System.Xml.Serialization.XmlElementAttribute("carrierSpecialService", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CarrierSpecialServiceType> CarrierSpecialService
        {
            get
            {
                return _carrierSpecialService;
            }
            private set
            {
                _carrierSpecialService = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CarrierSpecialService collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CarrierSpecialServiceSpecified
        {
            get
            {
                return (this.CarrierSpecialService.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CarrierSpecialServiceCollection" /> class.</para>
        /// </summary>
        public CarrierSpecialServiceCollection()
        {
            this._carrierSpecialService = new System.Collections.ObjectModel.Collection<CarrierSpecialServiceType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemOptionCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemOptionCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemOptionType> _itemOption;
        
        [System.Xml.Serialization.XmlElementAttribute("itemOption", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ItemOptionType> ItemOption
        {
            get
            {
                return _itemOption;
            }
            private set
            {
                _itemOption = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the ItemOption collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemOptionSpecified
        {
            get
            {
                return (this.ItemOption.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ItemOptionCollection" /> class.</para>
        /// </summary>
        public ItemOptionCollection()
        {
            this._itemOption = new System.Collections.ObjectModel.Collection<ItemOptionType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemOptionType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemOptionType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("optionName")]
        public string OptionName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("optionValue")]
        public string OptionValue { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelsCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelsCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ChannelFieldType> _channel;
        
        [System.Xml.Serialization.XmlElementAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ChannelFieldType> Channel
        {
            get
            {
                return _channel;
            }
            private set
            {
                _channel = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Channel collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelSpecified
        {
            get
            {
                return (this.Channel.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ChannelsCollection" /> class.</para>
        /// </summary>
        public ChannelsCollection()
        {
            this._channel = new System.Collections.ObjectModel.Collection<ChannelFieldType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelFieldType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelFieldType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("feedName")]
        public string FeedName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("jobName")]
        public string JobName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("active")]
        public bool Active { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Active property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ref1")]
        public string Ref1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref2")]
        public string Ref2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref3")]
        public string Ref3 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref4")]
        public string Ref4 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref5")]
        public string Ref5 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef1")]
        public string SecRef1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef2")]
        public string SecRef2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef3")]
        public string SecRef3 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef4")]
        public string SecRef4 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef5")]
        public string SecRef5 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("customerPackKey")]
        public string CustomerPackKey { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("quantityInPack")]
        public int QuantityInPack { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the QuantityInPack property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantityInPackSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelsListing", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelsListing
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ChannelListingType> _channel;
        
        [System.Xml.Serialization.XmlElementAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ChannelListingType> Channel
        {
            get
            {
                return _channel;
            }
            private set
            {
                _channel = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Channel collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelSpecified
        {
            get
            {
                return (this.Channel.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ChannelsListing" /> class.</para>
        /// </summary>
        public ChannelsListing()
        {
            this._channel = new System.Collections.ObjectModel.Collection<ChannelListingType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelListingType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelListingType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("feedName")]
        public string FeedName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("jobName")]
        public string JobName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("price")]
        public double Price { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Price property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("itemCondition")]
        public string ItemCondition { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("listingStatus")]
        public string ListingStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("saleable")]
        public bool Saleable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Saleable property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleableSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("active")]
        public bool Active { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Active property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public string Status { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("listingPrice")]
        public double ListingPrice { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ListingPrice property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListingPriceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("packQuantity")]
        public double PackQuantity { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PackQuantity property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackQuantitySpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("syncInventory")]
        public bool SyncInventory { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SyncInventory property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SyncInventorySpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("optionValue")]
        public string OptionValue { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("optionName")]
        public string OptionName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ref1")]
        public string Ref1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref2")]
        public string Ref2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref3")]
        public string Ref3 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref4")]
        public string Ref4 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref5")]
        public string Ref5 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef1")]
        public string SecRef1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef2")]
        public string SecRef2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef3")]
        public string SecRef3 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef4")]
        public string SecRef4 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef5")]
        public string SecRef5 { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelsResourceCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelsResourceCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ChannelResourceFieldType> _channel;
        
        [System.Xml.Serialization.XmlElementAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ChannelResourceFieldType> Channel
        {
            get
            {
                return _channel;
            }
            private set
            {
                _channel = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Channel collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelSpecified
        {
            get
            {
                return (this.Channel.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ChannelsResourceCollection" /> class.</para>
        /// </summary>
        public ChannelsResourceCollection()
        {
            this._channel = new System.Collections.ObjectModel.Collection<ChannelResourceFieldType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelResourceFieldType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelResourceFieldType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("businessUnit")]
        public string BusinessUnit { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("businessKey")]
        public string BusinessKey { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("otherKey")]
        public string OtherKey { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("entityType")]
        public string EntityType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("feedName")]
        public string FeedName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("jobName")]
        public string JobName { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("description")]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("price")]
        public double Price { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Price property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PriceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("itemCondition")]
        public string ItemCondition { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("listingStatus")]
        public string ListingStatus { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("saleable")]
        public bool Saleable { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Saleable property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleableSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("status")]
        public string Status { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("listingPrice")]
        public double ListingPrice { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ListingPrice property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ListingPriceSpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("packQuantity")]
        public double PackQuantity { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the PackQuantity property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PackQuantitySpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("syncInventory")]
        public bool SyncInventory { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the SyncInventory property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SyncInventorySpecified { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("active")]
        public bool Active { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Active property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ActiveSpecified { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("ref1")]
        public string Ref1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref2")]
        public string Ref2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref3")]
        public string Ref3 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref4")]
        public string Ref4 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("ref5")]
        public string Ref5 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef1")]
        public string SecRef1 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef2")]
        public string SecRef2 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef3")]
        public string SecRef3 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef4")]
        public string SecRef4 { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("secRef5")]
        public string SecRef5 { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtendedEntityCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedEntityCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ExtendedEntityType> _entity;
        
        [System.Xml.Serialization.XmlElementAttribute("entity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ExtendedEntityType> Entity
        {
            get
            {
                return _entity;
            }
            private set
            {
                _entity = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Entity collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EntitySpecified
        {
            get
            {
                return (this.Entity.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ExtendedEntityCollection" /> class.</para>
        /// </summary>
        public ExtendedEntityCollection()
        {
            this._entity = new System.Collections.ObjectModel.Collection<ExtendedEntityType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtendedEntityType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedEntityType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ExtendedFieldType> _field;
        
        [System.Xml.Serialization.XmlElementAttribute("field", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ExtendedFieldType> Field
        {
            get
            {
                return _field;
            }
            private set
            {
                _field = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Field collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FieldSpecified
        {
            get
            {
                return (this.Field.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ExtendedEntityType" /> class.</para>
        /// </summary>
        public ExtendedEntityType()
        {
            this._field = new System.Collections.ObjectModel.Collection<ExtendedFieldType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("key-field")]
        public string KeyField { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("key-value")]
        public string KeyValue { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ExtendedFieldType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExtendedFieldType
    {
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CustomAttributeCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomAttributeCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CustomAttributeType> _customAttribute;
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CustomAttributeType> CustomAttribute
        {
            get
            {
                return _customAttribute;
            }
            private set
            {
                _customAttribute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the CustomAttribute collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomAttributeSpecified
        {
            get
            {
                return (this.CustomAttribute.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="CustomAttributeCollection" /> class.</para>
        /// </summary>
        public CustomAttributeCollection()
        {
            this._customAttribute = new System.Collections.ObjectModel.Collection<CustomAttributeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CustomAttributeType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomAttributeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AddressType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("contactName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("attention", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attention { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("email", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("phone", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("phone2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone2 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("addressLine1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressLine1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("addressLine2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressLine2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("addressLine3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressLine3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("addressLine4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressLine4 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("city", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("stateProvinceCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StateProvinceCode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("postalCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostalCode { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("countryCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CountryCode { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AddressValidationOptionsType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressValidationOptionsType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("carrier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Carrier { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("profileName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProfileName { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _maxSuggestedAddresses = "0";
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("maxSuggestedAddresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaxSuggestedAddresses
        {
            get
            {
                return _maxSuggestedAddresses;
            }
            set
            {
                _maxSuggestedAddresses = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("streetLevel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool StreetLevel { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the StreetLevel property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StreetLevelSpecified { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AddressTypeCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddressTypeCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<AddressType> _address;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<AddressType> Address
        {
            get
            {
                return _address;
            }
            private set
            {
                _address = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="AddressTypeCollection" /> class.</para>
        /// </summary>
        public AddressTypeCollection()
        {
            this._address = new System.Collections.ObjectModel.Collection<AddressType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FreightType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FreightType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("termsType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public FreightTypeTermsType TermsType { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TermsType property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TermsTypeSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("account", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Account { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("billToPartner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BillToPartner { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("billToAddress", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AddressType BillToAddress { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("FreightTypeTermsType", Namespace="http://integration.deposco.com/types", AnonymousType=true)]
    public enum FreightTypeTermsType
    {
        
        Prepaid,
        
        Collect,
        
        [System.Xml.Serialization.XmlEnumAttribute("Third Party")]
        ThirdParty,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NoteType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoteType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private NoteTypeSource _source = Types.NoteTypeSource.Internal;
        
        [System.ComponentModel.DefaultValueAttribute(Types.NoteTypeSource.Internal)]
        [System.Xml.Serialization.XmlElementAttribute("source", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public NoteTypeSource Source
        {
            get
            {
                return _source;
            }
            set
            {
                _source = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("body", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Body { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("priority", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Priority { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NoteTypeSource", Namespace="http://integration.deposco.com/types", AnonymousType=true)]
    public enum NoteTypeSource
    {
        
        Internal,
        
        External,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NoteCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NoteCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NoteType> _note;
        
        [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<NoteType> Note
        {
            get
            {
                return _note;
            }
            private set
            {
                _note = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the Note collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoteSpecified
        {
            get
            {
                return (this.Note.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NoteCollection" /> class.</para>
        /// </summary>
        public NoteCollection()
        {
            this._note = new System.Collections.ObjectModel.Collection<NoteType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LinkType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LinkType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("rel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Rel { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("href", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Href { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PickDetailCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PickDetailCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PickDetailType> _pickDetail;
        
        [System.Xml.Serialization.XmlElementAttribute("pickDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PickDetailType> PickDetail
        {
            get
            {
                return _pickDetail;
            }
            private set
            {
                _pickDetail = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the PickDetail collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PickDetailSpecified
        {
            get
            {
                return (this.PickDetail.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="PickDetailCollection" /> class.</para>
        /// </summary>
        public PickDetailCollection()
        {
            this._pickDetail = new System.Collections.ObjectModel.Collection<PickDetailType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PickDetailType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PickDetailType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pickLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PickLocation { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pickQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double PickQuantity { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("packPicked", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pack.PackType PackPicked { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RetailActCollection", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetailActCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<RetailActType> _retailActivity;
        
        [System.Xml.Serialization.XmlElementAttribute("retailActivity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<RetailActType> RetailActivity
        {
            get
            {
                return _retailActivity;
            }
            private set
            {
                _retailActivity = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Gets a value indicating whether the RetailActivity collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RetailActivitySpecified
        {
            get
            {
                return (this.RetailActivity.Count != 0);
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="RetailActCollection" /> class.</para>
        /// </summary>
        public RetailActCollection()
        {
            this._retailActivity = new System.Collections.ObjectModel.Collection<RetailActType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RetailActType", Namespace="http://integration.deposco.com/types")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RetailActType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("createdDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreatedDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("updatedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime UpdatedDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("batch", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Batch { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("batchSequenceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long BatchSequenceNumber { get; set; }
        
        /// <summary>
        /// <para xml:lang="en">Gets or sets a value indicating whether the BatchSequenceNumber property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BatchSequenceNumberSpecified { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("transactionSource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionSource { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("retailTransactionId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RetailTransactionId { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sequenceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SequenceNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("referenceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("register", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Register { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("associate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Associate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("till", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Till { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("transactionStartDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime TransactionStartDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("transactionEndDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime TransactionEndDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("businessDayDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime BusinessDayDate { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("reasonCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReasonCode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _voided = false;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("voided", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Voided
        {
            get
            {
                return _voided;
            }
            set
            {
                _voided = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _testTransaction = false;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("testTransaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool TestTransaction
        {
            get
            {
                return _testTransaction;
            }
            set
            {
                _testTransaction = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("facility", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Facility { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("user", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User { get; set; }
    }
}
