//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace ChannelLookup
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelLookupCollection", Namespace="http://integration.deposco.com/channellookup")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("channelLookups", Namespace="http://integration.deposco.com/channellookup")]
    public partial class ChannelLookupCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ChannelLookupType> _channelLookup;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("channelLookup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ChannelLookupType> ChannelLookup
        {
            get
            {
                return _channelLookup;
            }
            private set
            {
                _channelLookup = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public ChannelLookupCollection()
        {
            this._channelLookup = new System.Collections.ObjectModel.Collection<ChannelLookupType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ChannelLookupType", Namespace="http://integration.deposco.com/channellookup")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChannelLookupType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tradingPartner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TradingPartner { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("integrationPoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntegrationPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("channelName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChannelName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("subType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SubType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Data { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("createdDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CreatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                if (this.CreatedDateValueSpecified)
                {
                    return this.CreatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CreatedDateValue = value.GetValueOrDefault();
                this.CreatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("updatedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime UpdatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UpdatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                if (this.UpdatedDateValueSpecified)
                {
                    return this.UpdatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UpdatedDateValue = value.GetValueOrDefault();
                this.UpdatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("createdBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreatedBy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("updatedBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UpdatedBy { get; set; }
    }
}
