//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace CoContact
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoContactType", Namespace="http://integration.deposco.com/cocontact")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("contact", Namespace="http://integration.deposco.com/cocontact")]
    public partial class CoContactType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("firstName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("middleName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MiddleName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lastName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nameSuffix", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameSuffix { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("namePrefix", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NamePrefix { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("attention", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Attention { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("contactName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("phone1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("phone2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Phone2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("email1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("email2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("addressNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AddressNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Types.AddressType Address { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("createdDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CreatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                if (this.CreatedDateValueSpecified)
                {
                    return this.CreatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CreatedDateValue = value.GetValueOrDefault();
                this.CreatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("updatedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime UpdatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UpdatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                if (this.UpdatedDateValueSpecified)
                {
                    return this.UpdatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UpdatedDateValue = value.GetValueOrDefault();
                this.UpdatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code { get; set; }
    }
}
