//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace CoLineSite
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OrderLineSiteCollection", Namespace="http://integration.deposco.com/colinesite")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("orderLineSites", Namespace="http://integration.deposco.com/colinesite")]
    public partial class OrderLineSiteCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<OrderLineSiteType> _orderLineSite;
        
        [System.Xml.Serialization.XmlElementAttribute("orderLineSite", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<OrderLineSiteType> OrderLineSite
        {
            get
            {
                return _orderLineSite;
            }
            private set
            {
                _orderLineSite = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderLineSiteSpecified
        {
            get
            {
                return (this.OrderLineSite.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public OrderLineSiteCollection()
        {
            this._orderLineSite = new System.Collections.ObjectModel.Collection<OrderLineSiteType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OrderLineSiteType", Namespace="http://integration.deposco.com/colinesite")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OrderLineSiteType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("tradingPartnerSite", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TradingPartnerSite { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("orderQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double OrderQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool OrderQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> OrderQuantity
        {
            get
            {
                if (this.OrderQuantityValueSpecified)
                {
                    return this.OrderQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OrderQuantityValue = value.GetValueOrDefault();
                this.OrderQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("shippedQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ShippedQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ShippedQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> ShippedQuantity
        {
            get
            {
                if (this.ShippedQuantityValueSpecified)
                {
                    return this.ShippedQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ShippedQuantityValue = value.GetValueOrDefault();
                this.ShippedQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("canceledQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double CanceledQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CanceledQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> CanceledQuantity
        {
            get
            {
                if (this.CanceledQuantityValueSpecified)
                {
                    return this.CanceledQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CanceledQuantityValue = value.GetValueOrDefault();
                this.CanceledQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoDate.CoDateType> _coDates;
        
        [System.Xml.Serialization.XmlArrayAttribute("coDates", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("coDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CoDate.CoDateType> CoDates
        {
            get
            {
                return _coDates;
            }
            private set
            {
                _coDates = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoDatesSpecified
        {
            get
            {
                return (this.CoDates.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public OrderLineSiteType()
        {
            this._coDates = new System.Collections.ObjectModel.Collection<CoDate.CoDateType>();
            this._references = new System.Collections.ObjectModel.Collection<CoReference.CoReferenceType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoReference.CoReferenceType> _references;
        
        [System.Xml.Serialization.XmlArrayAttribute("references", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("reference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CoReference.CoReferenceType> References
        {
            get
            {
                return _references;
            }
            private set
            {
                _references = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencesSpecified
        {
            get
            {
                return (this.References.Count != 0);
            }
        }
    }
}
