//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace CoManagementProfile
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ManagementProfileType", Namespace="http://integration.deposco.com/coManagementProfile")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("managementProfile", Namespace="http://integration.deposco.com/coManagementProfile")]
    public partial class ManagementProfileType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("fulfillmentMode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FulfillmentMode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("acknowledgementType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AcknowledgementType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("coRevisionMode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CoRevisionMode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("orderType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderType { get; set; }
    }
}
