//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace CoPayment
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoPaymentCollection", Namespace="http://integration.deposco.com/copayment")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("payments", Namespace="http://integration.deposco.com/copayment")]
    public partial class CoPaymentCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoPaymentType> _payment;
        
        [System.Xml.Serialization.XmlElementAttribute("payment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CoPaymentType> Payment
        {
            get
            {
                return _payment;
            }
            private set
            {
                _payment = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentSpecified
        {
            get
            {
                return (this.Payment.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public CoPaymentCollection()
        {
            this._payment = new System.Collections.ObjectModel.Collection<CoPaymentType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoPaymentType", Namespace="http://integration.deposco.com/copayment")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoPaymentType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PaymentType Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("currencyCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyCode { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("amount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double AmountValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AmountValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> Amount
        {
            get
            {
                if (this.AmountValueSpecified)
                {
                    return this.AmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AmountValue = value.GetValueOrDefault();
                this.AmountValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("cardType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CardType { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("debitCard", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DebitCardValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DebitCardValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> DebitCard
        {
            get
            {
                if (this.DebitCardValueSpecified)
                {
                    return this.DebitCardValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DebitCardValue = value.GetValueOrDefault();
                this.DebitCardValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("customerPresent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CustomerPresentValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CustomerPresentValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> CustomerPresent
        {
            get
            {
                if (this.CustomerPresentValueSpecified)
                {
                    return this.CustomerPresentValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CustomerPresentValue = value.GetValueOrDefault();
                this.CustomerPresentValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("authorizationNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AuthorizationNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("authorizationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime AuthorizationDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AuthorizationDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> AuthorizationDate
        {
            get
            {
                if (this.AuthorizationDateValueSpecified)
                {
                    return this.AuthorizationDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AuthorizationDateValue = value.GetValueOrDefault();
                this.AuthorizationDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("authorizationCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AuthorizationCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("authorizationMessage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AuthorizationMessage { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("authorized", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AuthorizedValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AuthorizedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Authorized
        {
            get
            {
                if (this.AuthorizedValueSpecified)
                {
                    return this.AuthorizedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AuthorizedValue = value.GetValueOrDefault();
                this.AuthorizedValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("authorizationOnly", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AuthorizationOnlyValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AuthorizationOnlyValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> AuthorizationOnly
        {
            get
            {
                if (this.AuthorizationOnlyValueSpecified)
                {
                    return this.AuthorizationOnlyValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AuthorizationOnlyValue = value.GetValueOrDefault();
                this.AuthorizationOnlyValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("paymentNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("parentPaymentNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentPaymentNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("paymentMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentMethod { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("gatewayName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GatewayName { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("voided", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool VoidedValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool VoidedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Voided
        {
            get
            {
                if (this.VoidedValueSpecified)
                {
                    return this.VoidedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.VoidedValue = value.GetValueOrDefault();
                this.VoidedValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("additionalData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AdditionalData { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("testTransaction", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool TestTransactionValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TestTransactionValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> TestTransaction
        {
            get
            {
                if (this.TestTransactionValueSpecified)
                {
                    return this.TestTransactionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TestTransactionValue = value.GetValueOrDefault();
                this.TestTransactionValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PaymentType", Namespace="http://integration.deposco.com/copayment")]
    [System.Xml.Serialization.XmlRootAttribute("PaymentType", Namespace="http://integration.deposco.com/copayment")]
    public enum PaymentType
    {
        
        Sale,
        
        Return,
        
        Authorization,
        
        Capture,
        
        Payment,
        
        Refund,
        
        Void,
    }
}
