//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace CoRefund
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoRefundCollection", Namespace="http://integration.deposco.com/corefund")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("refunds", Namespace="http://integration.deposco.com/corefund")]
    public partial class CoRefundCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoRefundType> _refund;
        
        [System.Xml.Serialization.XmlElementAttribute("refund", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CoRefundType> Refund
        {
            get
            {
                return _refund;
            }
            private set
            {
                _refund = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RefundSpecified
        {
            get
            {
                return (this.Refund.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public CoRefundCollection()
        {
            this._refund = new System.Collections.ObjectModel.Collection<CoRefundType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoRefundType", Namespace="http://integration.deposco.com/corefund")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoRefundType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("referenceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReferenceNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("currencyCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyCode { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("total", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TotalValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TotalValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> Total
        {
            get
            {
                if (this.TotalValueSpecified)
                {
                    return this.TotalValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TotalValue = value.GetValueOrDefault();
                this.TotalValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("subTotal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double SubTotalValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SubTotalValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> SubTotal
        {
            get
            {
                if (this.SubTotalValueSpecified)
                {
                    return this.SubTotalValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SubTotalValue = value.GetValueOrDefault();
                this.SubTotalValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("taxTotal", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TaxTotalValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TaxTotalValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> TaxTotal
        {
            get
            {
                if (this.TaxTotalValueSpecified)
                {
                    return this.TaxTotalValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TaxTotalValue = value.GetValueOrDefault();
                this.TaxTotalValueSpecified = value.HasValue;
            }
        }
    }
}
