//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace CoReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CoReferenceCollection", Namespace="http://integration.deposco.com/coreference")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("references", Namespace="http://integration.deposco.com/coreference")]
    public partial class CoReferenceCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoReferenceType> _reference;
        
        [System.Xml.Serialization.XmlElementAttribute("reference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CoReferenceType> Reference
        {
            get
            {
                return _reference;
            }
            private set
            {
                _reference = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceSpecified
        {
            get
            {
                return (this.Reference.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public CoReferenceCollection()
        {
            this._reference = new System.Collections.ObjectModel.Collection<CoReferenceType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("coReferenceType", Namespace="http://integration.deposco.com/coreference")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CoReferenceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("qualifier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Qualifier { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("value2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("value3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("value4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value4 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("value5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Value5 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
    }
}
