//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace CoTax
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TaxCollection", Namespace="http://integration.deposco.com/cotax")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("taxes", Namespace="http://integration.deposco.com/cotax")]
    public partial class TaxCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TaxType> _tax;
        
        [System.Xml.Serialization.XmlElementAttribute("tax", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TaxType> Tax
        {
            get
            {
                return _tax;
            }
            private set
            {
                _tax = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxSpecified
        {
            get
            {
                return (this.Tax.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public TaxCollection()
        {
            this._tax = new System.Collections.ObjectModel.Collection<TaxType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TaxType", Namespace="http://integration.deposco.com/cotax")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaxType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("taxType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaxTypeProperty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("taxExemptCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TaxExemptCode { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("taxAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TaxAmountValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TaxAmountValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> TaxAmount
        {
            get
            {
                if (this.TaxAmountValueSpecified)
                {
                    return this.TaxAmountValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TaxAmountValue = value.GetValueOrDefault();
                this.TaxAmountValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("taxPercentage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TaxPercentageValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TaxPercentageValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> TaxPercentage
        {
            get
            {
                if (this.TaxPercentageValueSpecified)
                {
                    return this.TaxPercentageValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TaxPercentageValue = value.GetValueOrDefault();
                this.TaxPercentageValueSpecified = value.HasValue;
            }
        }
    }
}
