//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace Customer
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CxCustomerCollection", Namespace="http://integration.deposco.com/customer")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("customers", Namespace="http://integration.deposco.com/customer")]
    public partial class CxCustomerCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CxCustomerType> _customer;
        
        [System.Xml.Serialization.XmlElementAttribute("customer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CxCustomerType> Customer
        {
            get
            {
                return _customer;
            }
            private set
            {
                _customer = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomerSpecified
        {
            get
            {
                return (this.Customer.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public CxCustomerCollection()
        {
            this._customer = new System.Collections.ObjectModel.Collection<CxCustomerType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CxCustomerType", Namespace="http://integration.deposco.com/customer")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CxCustomerType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IdValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IdValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Id
        {
            get
            {
                if (this.IdValueSpecified)
                {
                    return this.IdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IdValue = value.GetValueOrDefault();
                this.IdValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Number { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("firstName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FirstName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("middleName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MiddleName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lastName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LastName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("namePrefix", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NamePrefix { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nameSuffix", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameSuffix { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("birthDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime BirthDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BirthDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                if (this.BirthDateValueSpecified)
                {
                    return this.BirthDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BirthDateValue = value.GetValueOrDefault();
                this.BirthDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("gender", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Gender { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("source", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Source { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("externalCustomerNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExternalCustomerNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("otherReferenceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OtherReferenceNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("importReference", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImportReference { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("registrationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime RegistrationDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool RegistrationDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> RegistrationDate
        {
            get
            {
                if (this.RegistrationDateValueSpecified)
                {
                    return this.RegistrationDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RegistrationDateValue = value.GetValueOrDefault();
                this.RegistrationDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("registrationLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RegistrationLocation { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("firstTransactionDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime FirstTransactionDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool FirstTransactionDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> FirstTransactionDate
        {
            get
            {
                if (this.FirstTransactionDateValueSpecified)
                {
                    return this.FirstTransactionDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.FirstTransactionDateValue = value.GetValueOrDefault();
                this.FirstTransactionDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("lastTransactionDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime LastTransactionDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool LastTransactionDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> LastTransactionDate
        {
            get
            {
                if (this.LastTransactionDateValueSpecified)
                {
                    return this.LastTransactionDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.LastTransactionDateValue = value.GetValueOrDefault();
                this.LastTransactionDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _taxExempt = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlElementAttribute("taxExempt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool TaxExempt
        {
            get
            {
                return _taxExempt;
            }
            set
            {
                _taxExempt = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("educationLevel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EducationLevel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("maritalStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaritalStatus { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _acceptsMarketing = false;
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        [System.Xml.Serialization.XmlElementAttribute("acceptsMarketing", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AcceptsMarketing
        {
            get
            {
                return _acceptsMarketing;
            }
            set
            {
                _acceptsMarketing = value;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("acceptsMarketingUpdatedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime AcceptsMarketingUpdatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AcceptsMarketingUpdatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> AcceptsMarketingUpdatedDate
        {
            get
            {
                if (this.AcceptsMarketingUpdatedDateValueSpecified)
                {
                    return this.AcceptsMarketingUpdatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AcceptsMarketingUpdatedDateValue = value.GetValueOrDefault();
                this.AcceptsMarketingUpdatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("employeeNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmployeeNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ucceanNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UcceanNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("accountStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccountStatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("doingBusinessAs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DoingBusinessAs { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("paymentTerms", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentTerms { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("sequenceSSCCBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SequenceSsccBy { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("taxRate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double TaxRateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool TaxRateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> TaxRate
        {
            get
            {
                if (this.TaxRateValueSpecified)
                {
                    return this.TaxRateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TaxRateValue = value.GetValueOrDefault();
                this.TaxRateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("sendASN", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int SendAsnValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SendAsnValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> SendAsn
        {
            get
            {
                if (this.SendAsnValueSpecified)
                {
                    return this.SendAsnValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SendAsnValue = value.GetValueOrDefault();
                this.SendAsnValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("packingSlipLevel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackingSlipLevel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("packingSlipReport", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackingSlipReport { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("zplLabelReport", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZplLabelReport { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("useShipFromForShipments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool UseShipFromForShipmentsValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UseShipFromForShipmentsValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> UseShipFromForShipments
        {
            get
            {
                if (this.UseShipFromForShipmentsValueSpecified)
                {
                    return this.UseShipFromForShipmentsValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UseShipFromForShipmentsValue = value.GetValueOrDefault();
                this.UseShipFromForShipmentsValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("groupASNBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GroupAsnBy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("groupPalletBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string GroupPalletBy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("salesChannel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SalesChannel { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("priceList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PriceList { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("createdDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CreatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                if (this.CreatedDateValueSpecified)
                {
                    return this.CreatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CreatedDateValue = value.GetValueOrDefault();
                this.CreatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("updatedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime UpdatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UpdatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                if (this.UpdatedDateValueSpecified)
                {
                    return this.UpdatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UpdatedDateValue = value.GetValueOrDefault();
                this.UpdatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContactMethod.CxCustomerContactMethodType> _contactMethods;
        
        [System.Xml.Serialization.XmlArrayAttribute("contactMethods", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contactMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ContactMethod.CxCustomerContactMethodType> ContactMethods
        {
            get
            {
                return _contactMethods;
            }
            private set
            {
                _contactMethods = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContactMethodsSpecified
        {
            get
            {
                return (this.ContactMethods.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public CxCustomerType()
        {
            this._contactMethods = new System.Collections.ObjectModel.Collection<ContactMethod.CxCustomerContactMethodType>();
            this._addresses = new System.Collections.ObjectModel.Collection<Address.CxAddressType>();
            this._tradingPartnerSites = new System.Collections.ObjectModel.Collection<TradingPartnerSite.TradingPartnerSiteType>();
            this._notes = new System.Collections.ObjectModel.Collection<Types.NoteType>();
            this._customerOrders = new System.Collections.ObjectModel.Collection<CoHeader.CustomerOrderType>();
            this._channels = new System.Collections.ObjectModel.Collection<Types.ChannelFieldType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Address.CxAddressType> _addresses;
        
        [System.Xml.Serialization.XmlArrayAttribute("addresses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Address.CxAddressType> Addresses
        {
            get
            {
                return _addresses;
            }
            private set
            {
                _addresses = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AddressesSpecified
        {
            get
            {
                return (this.Addresses.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<TradingPartnerSite.TradingPartnerSiteType> _tradingPartnerSites;
        
        [System.Xml.Serialization.XmlArrayAttribute("tradingPartnerSites", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tradingPartnerSite", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<TradingPartnerSite.TradingPartnerSiteType> TradingPartnerSites
        {
            get
            {
                return _tradingPartnerSites;
            }
            private set
            {
                _tradingPartnerSites = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TradingPartnerSitesSpecified
        {
            get
            {
                return (this.TradingPartnerSites.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.NoteType> _notes;
        
        [System.Xml.Serialization.XmlArrayAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.NoteType> Notes
        {
            get
            {
                return _notes;
            }
            private set
            {
                _notes = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotesSpecified
        {
            get
            {
                return (this.Notes.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<CoHeader.CustomerOrderType> _customerOrders;
        
        [System.Xml.Serialization.XmlArrayAttribute("customerOrders", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customerOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<CoHeader.CustomerOrderType> CustomerOrders
        {
            get
            {
                return _customerOrders;
            }
            private set
            {
                _customerOrders = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomerOrdersSpecified
        {
            get
            {
                return (this.CustomerOrders.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.ChannelFieldType> _channels;
        
        [System.Xml.Serialization.XmlArrayAttribute("channels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.ChannelFieldType> Channels
        {
            get
            {
                return _channels;
            }
            private set
            {
                _channels = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelsSpecified
        {
            get
            {
                return (this.Channels.Count != 0);
            }
        }
    }
}
