//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace Gl
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GLCollection", Namespace="http://integration.deposco.com/gl")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("details", Namespace="http://integration.deposco.com/gl")]
    public partial class GlCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<GlType> _detail;
        
        [System.Xml.Serialization.XmlElementAttribute("detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<GlType> Detail
        {
            get
            {
                return _detail;
            }
            private set
            {
                _detail = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DetailSpecified
        {
            get
            {
                return (this.Detail.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public GlCollection()
        {
            this._detail = new System.Collections.ObjectModel.Collection<GlType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GLType", Namespace="http://integration.deposco.com/gl")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GlType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IdValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IdValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Id
        {
            get
            {
                if (this.IdValueSpecified)
                {
                    return this.IdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IdValue = value.GetValueOrDefault();
                this.IdValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("company", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Company { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("transactionNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TransactionNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("accountNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("actionType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActionType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("price", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double PriceValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PriceValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> Price
        {
            get
            {
                if (this.PriceValueSpecified)
                {
                    return this.PriceValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PriceValue = value.GetValueOrDefault();
                this.PriceValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("effectiveDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime EffectiveDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EffectiveDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> EffectiveDate
        {
            get
            {
                if (this.EffectiveDateValueSpecified)
                {
                    return this.EffectiveDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EffectiveDateValue = value.GetValueOrDefault();
                this.EffectiveDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("itemSku", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemSku { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("poNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PoNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int QuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool QuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Quantity
        {
            get
            {
                if (this.QuantityValueSpecified)
                {
                    return this.QuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.QuantityValue = value.GetValueOrDefault();
                this.QuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("reasonCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReasonCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("mailCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MailCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("state", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string State { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("city", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string City { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("zip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zip { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Address { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("purchasingCompany", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PurchasingCompany { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("costCenterName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CostCenterName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("facilityNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FacilityNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryLineNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryLineNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("packKey", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackKey { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customField1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomField1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customField2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomField2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customField3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomField3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryCondition { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute4 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute5 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute6", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute6 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute7", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute7 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lotNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LotNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("serialNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("bornOnDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime BornOnDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BornOnDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> BornOnDate
        {
            get
            {
                if (this.BornOnDateValueSpecified)
                {
                    return this.BornOnDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BornOnDateValue = value.GetValueOrDefault();
                this.BornOnDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("expirationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ExpirationDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ExpirationDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                if (this.ExpirationDateValueSpecified)
                {
                    return this.ExpirationDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExpirationDateValue = value.GetValueOrDefault();
                this.ExpirationDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.NoteType> _notes;
        
        [System.Xml.Serialization.XmlArrayAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.NoteType> Notes
        {
            get
            {
                return _notes;
            }
            private set
            {
                _notes = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotesSpecified
        {
            get
            {
                return (this.Notes.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public GlType()
        {
            this._notes = new System.Collections.ObjectModel.Collection<Types.NoteType>();
        }
    }
}
