//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace InventoryNoticeActivity
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InventoryNoticeActivityCollection", Namespace="http://integration.deposco.com/inventorynoticeactivity")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("inventoryNoticeActivities", Namespace="http://integration.deposco.com/inventorynoticeactivity")]
    public partial class InventoryNoticeActivityCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<InventoryNoticeActivityType> _inventoryNoticeActivity;
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryNoticeActivity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<InventoryNoticeActivityType> InventoryNoticeActivity
        {
            get
            {
                return _inventoryNoticeActivity;
            }
            private set
            {
                _inventoryNoticeActivity = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InventoryNoticeActivitySpecified
        {
            get
            {
                return (this.InventoryNoticeActivity.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public InventoryNoticeActivityCollection()
        {
            this._inventoryNoticeActivity = new System.Collections.ObjectModel.Collection<InventoryNoticeActivityType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("InventoryNoticeActivityType", Namespace="http://integration.deposco.com/inventorynoticeactivity")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InventoryNoticeActivityType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.ChannelListingType> _channels;
        
        [System.Xml.Serialization.XmlArrayAttribute("channels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.ChannelListingType> Channels
        {
            get
            {
                return _channels;
            }
            private set
            {
                _channels = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelsSpecified
        {
            get
            {
                return (this.Channels.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public InventoryNoticeActivityType()
        {
            this._channels = new System.Collections.ObjectModel.Collection<Types.ChannelListingType>();
        }
        
        [System.Xml.Serialization.XmlElementAttribute("facility", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Facility { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int QuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool QuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Quantity
        {
            get
            {
                if (this.QuantityValueSpecified)
                {
                    return this.QuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.QuantityValue = value.GetValueOrDefault();
                this.QuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("activityType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ActivityType { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("segmentedActivity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool SegmentedActivityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SegmentedActivityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> SegmentedActivity
        {
            get
            {
                if (this.SegmentedActivityValueSpecified)
                {
                    return this.SegmentedActivityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SegmentedActivityValue = value.GetValueOrDefault();
                this.SegmentedActivityValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("code", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("externalOrderNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExternalOrderNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("externalLineNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExternalLineNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("noticeType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NoticeType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("integrationPoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string IntegrationPoint { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("segmentationType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SegmentationType { get; set; }
    }
}
