//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace ItemVendor
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemVendorCollection", Namespace="http://integration.deposco.com/itemVendor")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("itemVendors", Namespace="http://integration.deposco.com/itemVendor")]
    public partial class ItemVendorCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ItemVendorType> _itemVendor;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemVendor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ItemVendorType> ItemVendor
        {
            get
            {
                return _itemVendor;
            }
            private set
            {
                _itemVendor = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public ItemVendorCollection()
        {
            this._itemVendor = new System.Collections.ObjectModel.Collection<ItemVendorType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ItemVendorType", Namespace="http://integration.deposco.com/itemVendor")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ItemVendorType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BusinessUnit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Item.ItemType Item { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shortDescription", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShortDescription { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("longDescription", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LongDescription { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("tradingPartnerCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string TradingPartnerCode { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("reorderQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ReorderQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReorderQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> ReorderQuantity
        {
            get
            {
                if (this.ReorderQuantityValueSpecified)
                {
                    return this.ReorderQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReorderQuantityValue = value.GetValueOrDefault();
                this.ReorderQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("reorderPoint", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ReorderPointValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReorderPointValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> ReorderPoint
        {
            get
            {
                if (this.ReorderPointValueSpecified)
                {
                    return this.ReorderPointValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReorderPointValue = value.GetValueOrDefault();
                this.ReorderPointValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("reorderLeadTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ReorderLeadTimeValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReorderLeadTimeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> ReorderLeadTime
        {
            get
            {
                if (this.ReorderLeadTimeValueSpecified)
                {
                    return this.ReorderLeadTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReorderLeadTimeValue = value.GetValueOrDefault();
                this.ReorderLeadTimeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("unitCost", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double UnitCostValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UnitCostValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> UnitCost
        {
            get
            {
                if (this.UnitCostValueSpecified)
                {
                    return this.UnitCostValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UnitCostValue = value.GetValueOrDefault();
                this.UnitCostValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("fulfillmentType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FulfillmentType { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("isPreferred", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsPreferredValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsPreferredValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsPreferred
        {
            get
            {
                if (this.IsPreferredValueSpecified)
                {
                    return this.IsPreferredValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsPreferredValue = value.GetValueOrDefault();
                this.IsPreferredValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("isInventorySyncEnabled", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsInventorySyncEnabledValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsInventorySyncEnabledValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsInventorySyncEnabled
        {
            get
            {
                if (this.IsInventorySyncEnabledValueSpecified)
                {
                    return this.IsInventorySyncEnabledValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsInventorySyncEnabledValue = value.GetValueOrDefault();
                this.IsInventorySyncEnabledValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemSkuUpc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemSkuUpc { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("additionalCost", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double AdditionalCostValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool AdditionalCostValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> AdditionalCost
        {
            get
            {
                if (this.AdditionalCostValueSpecified)
                {
                    return this.AdditionalCostValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.AdditionalCostValue = value.GetValueOrDefault();
                this.AdditionalCostValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int QuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool QuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Quantity
        {
            get
            {
                if (this.QuantityValueSpecified)
                {
                    return this.QuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.QuantityValue = value.GetValueOrDefault();
                this.QuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("importReference1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImportReference1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("importReference2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ImportReference2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportReference1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExportReference1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportReference2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ExportReference2 { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("reorderLot", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ReorderLotValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReorderLotValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> ReorderLot
        {
            get
            {
                if (this.ReorderLotValueSpecified)
                {
                    return this.ReorderLotValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReorderLotValue = value.GetValueOrDefault();
                this.ReorderLotValueSpecified = value.HasValue;
            }
        }
    }
}
