//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace KitDetail
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KitDetailCollection", Namespace="http://integration.deposco.com/kitdetail")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("kitDetails", Namespace="http://integration.deposco.com/kitdetail")]
    public partial class KitDetailCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KitDetailType> _kitDetail;
        
        [System.Xml.Serialization.XmlElementAttribute("kitDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<KitDetailType> KitDetail
        {
            get
            {
                return _kitDetail;
            }
            private set
            {
                _kitDetail = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KitDetailSpecified
        {
            get
            {
                return (this.KitDetail.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public KitDetailCollection()
        {
            this._kitDetail = new System.Collections.ObjectModel.Collection<KitDetailType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KitDetailType", Namespace="http://integration.deposco.com/kitdetail")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KitDetailType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IdValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IdValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Id
        {
            get
            {
                if (this.IdValueSpecified)
                {
                    return this.IdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IdValue = value.GetValueOrDefault();
                this.IdValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int QuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool QuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Quantity
        {
            get
            {
                if (this.QuantityValueSpecified)
                {
                    return this.QuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.QuantityValue = value.GetValueOrDefault();
                this.QuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("rank", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RankValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool RankValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Rank
        {
            get
            {
                if (this.RankValueSpecified)
                {
                    return this.RankValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RankValue = value.GetValueOrDefault();
                this.RankValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("createdDateTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreatedDateTimeValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CreatedDateTimeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> CreatedDateTime
        {
            get
            {
                if (this.CreatedDateTimeValueSpecified)
                {
                    return this.CreatedDateTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CreatedDateTimeValue = value.GetValueOrDefault();
                this.CreatedDateTimeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("updatedDateTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime UpdatedDateTimeValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UpdatedDateTimeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UpdatedDateTime
        {
            get
            {
                if (this.UpdatedDateTimeValueSpecified)
                {
                    return this.UpdatedDateTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UpdatedDateTimeValue = value.GetValueOrDefault();
                this.UpdatedDateTimeValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("createdBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreatedBy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("updatedBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UpdatedBy { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pack.PackType Pack { get; set; }
    }
}
