//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace KitHeader
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KitHeaderCollection", Namespace="http://integration.deposco.com/kitheader")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("kitHeaders", Namespace="http://integration.deposco.com/kitheader")]
    public partial class KitHeaderCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KitHeaderType> _kitHeader;
        
        [System.Xml.Serialization.XmlElementAttribute("kitHeader", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<KitHeaderType> KitHeader
        {
            get
            {
                return _kitHeader;
            }
            private set
            {
                _kitHeader = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KitHeaderSpecified
        {
            get
            {
                return (this.KitHeader.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public KitHeaderCollection()
        {
            this._kitHeader = new System.Collections.ObjectModel.Collection<KitHeaderType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("KitHeaderType", Namespace="http://integration.deposco.com/kitheader")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class KitHeaderType
    {
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long IdValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IdValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<long> Id
        {
            get
            {
                if (this.IdValueSpecified)
                {
                    return this.IdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IdValue = value.GetValueOrDefault();
                this.IdValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("maxWorkorderSize", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MaxWorkorderSizeValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MaxWorkorderSizeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> MaxWorkorderSize
        {
            get
            {
                if (this.MaxWorkorderSizeValueSpecified)
                {
                    return this.MaxWorkorderSizeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MaxWorkorderSizeValue = value.GetValueOrDefault();
                this.MaxWorkorderSizeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("minWorkorderSize", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MinWorkorderSizeValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MinWorkorderSizeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> MinWorkorderSize
        {
            get
            {
                if (this.MinWorkorderSizeValueSpecified)
                {
                    return this.MinWorkorderSizeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MinWorkorderSizeValue = value.GetValueOrDefault();
                this.MinWorkorderSizeValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("kitUsage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KitUsage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute3 { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("createdDateTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreatedDateTimeValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CreatedDateTimeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> CreatedDateTime
        {
            get
            {
                if (this.CreatedDateTimeValueSpecified)
                {
                    return this.CreatedDateTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CreatedDateTimeValue = value.GetValueOrDefault();
                this.CreatedDateTimeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("updatedDateTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime UpdatedDateTimeValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UpdatedDateTimeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UpdatedDateTime
        {
            get
            {
                if (this.UpdatedDateTimeValueSpecified)
                {
                    return this.UpdatedDateTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UpdatedDateTimeValue = value.GetValueOrDefault();
                this.UpdatedDateTimeValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("createdBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CreatedBy { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("updatedBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UpdatedBy { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<KitDetail.KitDetailType> _kitDetails;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("kitDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("kitDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<KitDetail.KitDetailType> KitDetails
        {
            get
            {
                return _kitDetails;
            }
            private set
            {
                _kitDetails = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public KitHeaderType()
        {
            this._kitDetails = new System.Collections.ObjectModel.Collection<KitDetail.KitDetailType>();
            this._channels = new System.Collections.ObjectModel.Collection<Types.ChannelFieldType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.ChannelFieldType> _channels;
        
        [System.Xml.Serialization.XmlArrayAttribute("channels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.ChannelFieldType> Channels
        {
            get
            {
                return _channels;
            }
            private set
            {
                _channels = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelsSpecified
        {
            get
            {
                return (this.Channels.Count != 0);
            }
        }
    }
}
