//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace OrderStatus
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OrderStatusCollection", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("orders", Namespace="http://integration.deposco.com/orderstatus")]
    public partial class OrderStatusCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<OrderStatusType> _orderStatus;
        
        [System.Xml.Serialization.XmlElementAttribute("orderStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<OrderStatusType> OrderStatus
        {
            get
            {
                return _orderStatus;
            }
            private set
            {
                _orderStatus = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OrderStatusSpecified
        {
            get
            {
                return (this.OrderStatus.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public OrderStatusCollection()
        {
            this._orderStatus = new System.Collections.ObjectModel.Collection<OrderStatusType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("OrderStatusType", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("OrderStatusType", Namespace="http://integration.deposco.com/orderstatus")]
    public partial class OrderStatusType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("orderNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("orderStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("orderType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("orderSource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderSource { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customAttribute1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute1 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customAttribute2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute2 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customAttribute3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute3 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customAttribute4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute4 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customAttribute5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute5 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customAttribute6", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute6 { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customAttribute7", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute7 { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LineStatusType> _lines;
        
        [System.Xml.Serialization.XmlArrayAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<LineStatusType> Lines
        {
            get
            {
                return _lines;
            }
            private set
            {
                _lines = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LinesSpecified
        {
            get
            {
                return (this.Lines.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public OrderStatusType()
        {
            this._lines = new System.Collections.ObjectModel.Collection<LineStatusType>();
            this._shipments = new System.Collections.ObjectModel.Collection<ShipmentStatusType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ShipmentStatusType> _shipments;
        
        [System.Xml.Serialization.XmlArrayAttribute("shipments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("shipment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ShipmentStatusType> Shipments
        {
            get
            {
                return _shipments;
            }
            private set
            {
                _shipments = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentsSpecified
        {
            get
            {
                return (this.Shipments.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LineStatusCollection", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LineStatusCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LineStatusType> _line;
        
        [System.Xml.Serialization.XmlElementAttribute("line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<LineStatusType> Line
        {
            get
            {
                return _line;
            }
            private set
            {
                _line = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineSpecified
        {
            get
            {
                return (this.Line.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public LineStatusCollection()
        {
            this._line = new System.Collections.ObjectModel.Collection<LineStatusType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LineStatusType", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LineStatusType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lineNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customerLineNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerLineNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shipmentLineNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipmentLineNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lineStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("productCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductCategory { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("orderPackQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double OrderPackQuantity { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("shippedPackQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ShippedPackQuantity { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("receivedPackQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ReceivedPackQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReceivedPackQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> ReceivedPackQuantity
        {
            get
            {
                if (this.ReceivedPackQuantityValueSpecified)
                {
                    return this.ReceivedPackQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReceivedPackQuantityValue = value.GetValueOrDefault();
                this.ReceivedPackQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("soldPackQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double SoldPackQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SoldPackQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> SoldPackQuantity
        {
            get
            {
                if (this.SoldPackQuantityValueSpecified)
                {
                    return this.SoldPackQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SoldPackQuantityValue = value.GetValueOrDefault();
                this.SoldPackQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("shortagePackQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ShortagePackQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ShortagePackQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> ShortagePackQuantity
        {
            get
            {
                if (this.ShortagePackQuantityValueSpecified)
                {
                    return this.ShortagePackQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ShortagePackQuantityValue = value.GetValueOrDefault();
                this.ShortagePackQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("outOfStockQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double OutOfStockQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool OutOfStockQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> OutOfStockQuantity
        {
            get
            {
                if (this.OutOfStockQuantityValueSpecified)
                {
                    return this.OutOfStockQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OutOfStockQuantityValue = value.GetValueOrDefault();
                this.OutOfStockQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("pickedPackQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double PickedPackQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PickedPackQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> PickedPackQuantity
        {
            get
            {
                if (this.PickedPackQuantityValueSpecified)
                {
                    return this.PickedPackQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PickedPackQuantityValue = value.GetValueOrDefault();
                this.PickedPackQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pack.PackType Pack { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReceiptLineStatusType> _receiptLines;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("receiptLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("receiptLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ReceiptLineStatusType> ReceiptLines
        {
            get
            {
                return _receiptLines;
            }
            private set
            {
                _receiptLines = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public LineStatusType()
        {
            this._receiptLines = new System.Collections.ObjectModel.Collection<ReceiptLineStatusType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReceiptLineStatusCollection", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiptLineStatusCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReceiptLineStatusType> _receiptLine;
        
        [System.Xml.Serialization.XmlElementAttribute("receiptLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ReceiptLineStatusType> ReceiptLine
        {
            get
            {
                return _receiptLine;
            }
            private set
            {
                _receiptLine = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptLineSpecified
        {
            get
            {
                return (this.ReceiptLine.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public ReceiptLineStatusCollection()
        {
            this._receiptLine = new System.Collections.ObjectModel.Collection<ReceiptLineStatusType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReceiptLineStatusType", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiptLineStatusType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receiptLineNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiptLineNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receivedPackQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ReceivedPackQuantity { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receivedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ReceivedDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lpn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Lpn { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("lotNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LotNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("serialNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("bornOnDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime BornOnDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BornOnDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> BornOnDate
        {
            get
            {
                if (this.BornOnDateValueSpecified)
                {
                    return this.BornOnDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BornOnDateValue = value.GetValueOrDefault();
                this.BornOnDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("expirationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ExpirationDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ExpirationDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                if (this.ExpirationDateValueSpecified)
                {
                    return this.ExpirationDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExpirationDateValue = value.GetValueOrDefault();
                this.ExpirationDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("destination", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Destination { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("catchWeight", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double CatchWeightValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CatchWeightValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> CatchWeight
        {
            get
            {
                if (this.CatchWeightValueSpecified)
                {
                    return this.CatchWeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CatchWeightValue = value.GetValueOrDefault();
                this.CatchWeightValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pack.PackType Pack { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ShipmentStatusCollection", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShipmentStatusCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ShipmentStatusType> _shipment;
        
        [System.Xml.Serialization.XmlElementAttribute("shipment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ShipmentStatusType> Shipment
        {
            get
            {
                return _shipment;
            }
            private set
            {
                _shipment = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentSpecified
        {
            get
            {
                return (this.Shipment.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public ShipmentStatusCollection()
        {
            this._shipment = new System.Collections.ObjectModel.Collection<ShipmentStatusType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ShipmentStatusType", Namespace="http://integration.deposco.com/orderstatus")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShipmentStatusType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("shipmentNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipmentNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("shipmentStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipmentStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("shipmentCurrentStatus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipmentCurrentStatus { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("shipmentType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipmentType { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("carrier", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Carrier { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("method", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Method { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("trackingNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrackingNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("actualShipDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ActualShipDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ActualShipDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ActualShipDate
        {
            get
            {
                if (this.ActualShipDateValueSpecified)
                {
                    return this.ActualShipDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ActualShipDateValue = value.GetValueOrDefault();
                this.ActualShipDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("shippingCost", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double ShippingCostValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ShippingCostValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> ShippingCost
        {
            get
            {
                if (this.ShippingCostValueSpecified)
                {
                    return this.ShippingCostValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ShippingCostValue = value.GetValueOrDefault();
                this.ShippingCostValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LineStatusType> _lines;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("lines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("line", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<LineStatusType> Lines
        {
            get
            {
                return _lines;
            }
            private set
            {
                _lines = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public ShipmentStatusType()
        {
            this._lines = new System.Collections.ObjectModel.Collection<LineStatusType>();
        }
    }
}
