//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace Pack
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackCollection", Namespace="http://integration.deposco.com/pack")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("packs", Namespace="http://integration.deposco.com/pack")]
    public partial class PackCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PackType> _pack;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PackType> Pack
        {
            get
            {
                return _pack;
            }
            private set
            {
                _pack = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public PackCollection()
        {
            this._pack = new System.Collections.ObjectModel.Collection<PackType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PackType", Namespace="http://integration.deposco.com/pack")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PackType", Namespace="http://integration.deposco.com/pack")]
    public partial class PackType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Quantity { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("weight", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double WeightValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool WeightValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> Weight
        {
            get
            {
                if (this.WeightValueSpecified)
                {
                    return this.WeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.WeightValue = value.GetValueOrDefault();
                this.WeightValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("weightUOM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WeightUom { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BoxTypeType> _boxTypes;
        
        [System.Xml.Serialization.XmlArrayAttribute("boxTypes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("boxType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<BoxTypeType> BoxTypes
        {
            get
            {
                return _boxTypes;
            }
            private set
            {
                _boxTypes = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoxTypesSpecified
        {
            get
            {
                return (this.BoxTypes.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PackType()
        {
            this._boxTypes = new System.Collections.ObjectModel.Collection<BoxTypeType>();
            this._customMappings = new System.Collections.ObjectModel.Collection<Types.CustomMapType>();
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("dimension", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Types.DimensionType Dimension { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("upcs", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Upc.UpcCollection Upcs { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("newPackFlag", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool NewPackFlagValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool NewPackFlagValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> NewPackFlag
        {
            get
            {
                if (this.NewPackFlagValueSpecified)
                {
                    return this.NewPackFlagValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.NewPackFlagValue = value.GetValueOrDefault();
                this.NewPackFlagValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("lpnTrackingEnabled", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool LpnTrackingEnabledValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool LpnTrackingEnabledValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> LpnTrackingEnabled
        {
            get
            {
                if (this.LpnTrackingEnabledValueSpecified)
                {
                    return this.LpnTrackingEnabledValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.LpnTrackingEnabledValue = value.GetValueOrDefault();
                this.LpnTrackingEnabledValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("readyToShip", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ReadyToShipValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReadyToShipValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> ReadyToShip
        {
            get
            {
                if (this.ReadyToShipValueSpecified)
                {
                    return this.ReadyToShipValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReadyToShipValue = value.GetValueOrDefault();
                this.ReadyToShipValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.CustomMapType> _customMappings;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("customMappings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customMapping", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.CustomMapType> CustomMappings
        {
            get
            {
                return _customMappings;
            }
            private set
            {
                _customMappings = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("cartonGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CartonGroup { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("preferredCartonType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PreferredCartonType { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BoxTypeCollection", Namespace="http://integration.deposco.com/pack")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxTypeCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<BoxTypeType> _boxType;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("boxType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<BoxTypeType> BoxType
        {
            get
            {
                return _boxType;
            }
            private set
            {
                _boxType = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public BoxTypeCollection()
        {
            this._boxType = new System.Collections.ObjectModel.Collection<BoxTypeType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("BoxTypeType", Namespace="http://integration.deposco.com/pack")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoxTypeType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Quantity { get; set; }
    }
}
