//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace PostShipment
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PostShipmentCollection", Namespace="http://integration.deposco.com/postshipment")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("shipments", Namespace="http://integration.deposco.com/postshipment")]
    public partial class PostShipmentCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PostShipmentType> _shipment;
        
        [System.Xml.Serialization.XmlElementAttribute("shipment", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PostShipmentType> Shipment
        {
            get
            {
                return _shipment;
            }
            private set
            {
                _shipment = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ShipmentSpecified
        {
            get
            {
                return (this.Shipment.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PostShipmentCollection()
        {
            this._shipment = new System.Collections.ObjectModel.Collection<PostShipmentType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PostShipmentType", Namespace="http://integration.deposco.com/postshipment")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PostShipmentType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Number { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("plannedArrivalDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime PlannedArrivalDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PlannedArrivalDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> PlannedArrivalDate
        {
            get
            {
                if (this.PlannedArrivalDateValueSpecified)
                {
                    return this.PlannedArrivalDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PlannedArrivalDateValue = value.GetValueOrDefault();
                this.PlannedArrivalDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("plannedShipDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime PlannedShipDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool PlannedShipDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> PlannedShipDate
        {
            get
            {
                if (this.PlannedShipDateValueSpecified)
                {
                    return this.PlannedShipDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.PlannedShipDateValue = value.GetValueOrDefault();
                this.PlannedShipDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("actualShipDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ActualShipDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ActualShipDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ActualShipDate
        {
            get
            {
                if (this.ActualShipDateValueSpecified)
                {
                    return this.ActualShipDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ActualShipDateValue = value.GetValueOrDefault();
                this.ActualShipDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("billToAddress", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Types.AddressType BillToAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shipToAddress", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Types.AddressType ShipToAddress { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("shipToEmail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ShipToEmail { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.CustomAttributeType> _customAttributes;
        
        [System.Xml.Serialization.XmlArrayAttribute("customAttributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("customAttribute", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.CustomAttributeType> CustomAttributes
        {
            get
            {
                return _customAttributes;
            }
            private set
            {
                _customAttributes = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomAttributesSpecified
        {
            get
            {
                return (this.CustomAttributes.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PostShipmentType()
        {
            this._customAttributes = new System.Collections.ObjectModel.Collection<Types.CustomAttributeType>();
            this._notes = new System.Collections.ObjectModel.Collection<Types.NoteType>();
            this._containers = new System.Collections.ObjectModel.Collection<Container.ContainerType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.NoteType> _notes;
        
        [System.Xml.Serialization.XmlArrayAttribute("notes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.NoteType> Notes
        {
            get
            {
                return _notes;
            }
            private set
            {
                _notes = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NotesSpecified
        {
            get
            {
                return (this.Notes.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Container.ContainerType> _containers;
        
        [System.Xml.Serialization.XmlArrayAttribute("containers", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("container", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Container.ContainerType> Containers
        {
            get
            {
                return _containers;
            }
            private set
            {
                _containers = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ContainersSpecified
        {
            get
            {
                return (this.Containers.Count != 0);
            }
        }
    }
}
