//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace PrepAdviceDetail
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PrepAdviceDetailCollection", Namespace="http://integration.deposco.com/prepadvicedetail")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("prepAdviceDetails", Namespace="http://integration.deposco.com/prepadvicedetail")]
    public partial class PrepAdviceDetailCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrepAdviceDetailType> _prepAdviceDetail;
        
        [System.Xml.Serialization.XmlElementAttribute("prepAdviceDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PrepAdviceDetailType> PrepAdviceDetail
        {
            get
            {
                return _prepAdviceDetail;
            }
            private set
            {
                _prepAdviceDetail = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepAdviceDetailSpecified
        {
            get
            {
                return (this.PrepAdviceDetail.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PrepAdviceDetailCollection()
        {
            this._prepAdviceDetail = new System.Collections.ObjectModel.Collection<PrepAdviceDetailType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PrepAdviceDetailType", Namespace="http://integration.deposco.com/prepadvicedetail")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrepAdviceDetailType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("prepType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PrepType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Note { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("effectiveCost", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double EffectiveCostValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EffectiveCostValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> EffectiveCost
        {
            get
            {
                if (this.EffectiveCostValueSpecified)
                {
                    return this.EffectiveCostValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EffectiveCostValue = value.GetValueOrDefault();
                this.EffectiveCostValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("currencyCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyCode { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("effectiveStartDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime EffectiveStartDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EffectiveStartDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> EffectiveStartDate
        {
            get
            {
                if (this.EffectiveStartDateValueSpecified)
                {
                    return this.EffectiveStartDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EffectiveStartDateValue = value.GetValueOrDefault();
                this.EffectiveStartDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("effectiveEndDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime EffectiveEndDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool EffectiveEndDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> EffectiveEndDate
        {
            get
            {
                if (this.EffectiveEndDateValueSpecified)
                {
                    return this.EffectiveEndDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.EffectiveEndDateValue = value.GetValueOrDefault();
                this.EffectiveEndDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute3 { get; set; }
    }
}
