//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace PrepAdvice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PrepAdviceCollection", Namespace="http://integration.deposco.com/prepadvice")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("prepAdvices", Namespace="http://integration.deposco.com/prepadvice")]
    public partial class PrepAdviceCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrepAdviceType> _prepAdvice;
        
        [System.Xml.Serialization.XmlElementAttribute("prepAdvice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PrepAdviceType> PrepAdvice
        {
            get
            {
                return _prepAdvice;
            }
            private set
            {
                _prepAdvice = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepAdviceSpecified
        {
            get
            {
                return (this.PrepAdvice.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PrepAdviceCollection()
        {
            this._prepAdvice = new System.Collections.ObjectModel.Collection<PrepAdviceType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PrepAdviceType", Namespace="http://integration.deposco.com/prepadvice")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrepAdviceType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("tradingPartner", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TradingPartner { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("productCategory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductCategory { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("name", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("source", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Source { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("note", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Note { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrepAdviceDetail.PrepAdviceDetailType> _prepAdviceDetails;
        
        [System.Xml.Serialization.XmlArrayAttribute("prepAdviceDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prepAdviceDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PrepAdviceDetail.PrepAdviceDetailType> PrepAdviceDetails
        {
            get
            {
                return _prepAdviceDetails;
            }
            private set
            {
                _prepAdviceDetails = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepAdviceDetailsSpecified
        {
            get
            {
                return (this.PrepAdviceDetails.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PrepAdviceType()
        {
            this._prepAdviceDetails = new System.Collections.ObjectModel.Collection<PrepAdviceDetail.PrepAdviceDetailType>();
            this._prepItemPacks = new System.Collections.ObjectModel.Collection<PrepItemPackType>();
            this._channels = new System.Collections.ObjectModel.Collection<Types.ChannelFieldType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrepItemPackType> _prepItemPacks;
        
        [System.Xml.Serialization.XmlArrayAttribute("prepItemPacks", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prepItemPack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PrepItemPackType> PrepItemPacks
        {
            get
            {
                return _prepItemPacks;
            }
            private set
            {
                _prepItemPacks = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepItemPacksSpecified
        {
            get
            {
                return (this.PrepItemPacks.Count != 0);
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.ChannelFieldType> _channels;
        
        [System.Xml.Serialization.XmlArrayAttribute("channels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.ChannelFieldType> Channels
        {
            get
            {
                return _channels;
            }
            private set
            {
                _channels = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelsSpecified
        {
            get
            {
                return (this.Channels.Count != 0);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PrepItemPackCollection", Namespace="http://integration.deposco.com/prepadvice")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrepItemPackCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrepItemPackType> _prepItemPack;
        
        [System.Xml.Serialization.XmlElementAttribute("prepItemPack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PrepItemPackType> PrepItemPack
        {
            get
            {
                return _prepItemPack;
            }
            private set
            {
                _prepItemPack = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepItemPackSpecified
        {
            get
            {
                return (this.PrepItemPack.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public PrepItemPackCollection()
        {
            this._prepItemPack = new System.Collections.ObjectModel.Collection<PrepItemPackType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PrepItemPackType", Namespace="http://integration.deposco.com/prepadvice")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PrepItemPackType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("packQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PackQuantity { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<PrepAdviceDetail.PrepAdviceDetailType> _prepAdviceDetails;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("prepAdviceDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("prepAdviceDetail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<PrepAdviceDetail.PrepAdviceDetailType> PrepAdviceDetails
        {
            get
            {
                return _prepAdviceDetails;
            }
            private set
            {
                _prepAdviceDetails = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public PrepItemPackType()
        {
            this._prepAdviceDetails = new System.Collections.ObjectModel.Collection<PrepAdviceDetail.PrepAdviceDetailType>();
            this._channels = new System.Collections.ObjectModel.Collection<Types.ChannelFieldType>();
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.ChannelFieldType> _channels;
        
        [System.Xml.Serialization.XmlArrayAttribute("channels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.ChannelFieldType> Channels
        {
            get
            {
                return _channels;
            }
            private set
            {
                _channels = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChannelsSpecified
        {
            get
            {
                return (this.Channels.Count != 0);
            }
        }
    }
}
