//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace ReceiptAdvice
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReceiptAdviceCollection", Namespace="http://integration.deposco.com/receiptadvice")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("receivingAdvice", Namespace="http://integration.deposco.com/receiptadvice")]
    public partial class ReceiptAdviceCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReceiptAdviceType> _receiptAdvice;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receiptAdvice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ReceiptAdviceType> ReceiptAdvice
        {
            get
            {
                return _receiptAdvice;
            }
            private set
            {
                _receiptAdvice = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public ReceiptAdviceCollection()
        {
            this._receiptAdvice = new System.Collections.ObjectModel.Collection<ReceiptAdviceType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReceiptAdviceType", Namespace="http://integration.deposco.com/receiptadvice")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiptAdviceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receiptAdviceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceiptAdviceNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("orderNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("receivingFacility", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingFacility { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("receivedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ReceivedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReceivedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ReceivedDate
        {
            get
            {
                if (this.ReceivedDateValueSpecified)
                {
                    return this.ReceivedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReceivedDateValue = value.GetValueOrDefault();
                this.ReceivedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("customerOrderNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerOrderNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("asnNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AsnNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("createdDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime CreatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CreatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> CreatedDate
        {
            get
            {
                if (this.CreatedDateValueSpecified)
                {
                    return this.CreatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CreatedDateValue = value.GetValueOrDefault();
                this.CreatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("updatedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime UpdatedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UpdatedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> UpdatedDate
        {
            get
            {
                if (this.UpdatedDateValueSpecified)
                {
                    return this.UpdatedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UpdatedDateValue = value.GetValueOrDefault();
                this.UpdatedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReceiptItemAdvice.ReceiptItemAdviceType> _receiptItems;
        
        [System.Xml.Serialization.XmlArrayAttribute("receiptItems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("receiptItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ReceiptItemAdvice.ReceiptItemAdviceType> ReceiptItems
        {
            get
            {
                return _receiptItems;
            }
            private set
            {
                _receiptItems = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReceiptItemsSpecified
        {
            get
            {
                return (this.ReceiptItems.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public ReceiptAdviceType()
        {
            this._receiptItems = new System.Collections.ObjectModel.Collection<ReceiptItemAdvice.ReceiptItemAdviceType>();
        }
    }
}
