//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace Receiptline
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReceiptLineCollection", Namespace="http://integration.deposco.com/receiptline")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("receiptLines", Namespace="http://integration.deposco.com/receiptline")]
    public partial class ReceiptLineCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ReceiptLineType> _receiptLine;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receiptLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ReceiptLineType> ReceiptLine
        {
            get
            {
                return _receiptLine;
            }
            private set
            {
                _receiptLine = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public ReceiptLineCollection()
        {
            this._receiptLine = new System.Collections.ObjectModel.Collection<ReceiptLineType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ReceiptLineType", Namespace="http://integration.deposco.com/receiptline")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiptLineType
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _orderType = "Purchase Order";
        
        [System.ComponentModel.DefaultValueAttribute("Purchase Order")]
        [System.Xml.Serialization.XmlElementAttribute("orderType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderType
        {
            get
            {
                return _orderType;
            }
            set
            {
                _orderType = value;
            }
        }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("orderNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OrderNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lineNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LineNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("number", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Number { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("quantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Quantity { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _packType = "Each";
        
        [System.ComponentModel.DefaultValueAttribute("Each")]
        [System.Xml.Serialization.XmlElementAttribute("packType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PackType
        {
            get
            {
                return _packType;
            }
            set
            {
                _packType = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private int _packQty = 1;
        
        [System.ComponentModel.DefaultValueAttribute(1)]
        [System.Xml.Serialization.XmlElementAttribute("packQty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int PackQty
        {
            get
            {
                return _packQty;
            }
            set
            {
                _packQty = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("receivingFacility", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingFacility { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _receivingLocation = "Receiving";
        
        [System.ComponentModel.DefaultValueAttribute("Receiving")]
        [System.Xml.Serialization.XmlElementAttribute("receivingLocation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingLocation
        {
            get
            {
                return _receivingLocation;
            }
            set
            {
                _receivingLocation = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("receivingContainer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingContainer { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private string _receivingContainerType = "Pallet";
        
        [System.ComponentModel.DefaultValueAttribute("Pallet")]
        [System.Xml.Serialization.XmlElementAttribute("receivingContainerType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ReceivingContainerType
        {
            get
            {
                return _receivingContainerType;
            }
            set
            {
                _receivingContainerType = value;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("receivedDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ReceivedDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ReceivedDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ReceivedDate
        {
            get
            {
                if (this.ReceivedDateValueSpecified)
                {
                    return this.ReceivedDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ReceivedDateValue = value.GetValueOrDefault();
                this.ReceivedDateValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("unitPrice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double UnitPriceValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool UnitPriceValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> UnitPrice
        {
            get
            {
                if (this.UnitPriceValueSpecified)
                {
                    return this.UnitPriceValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.UnitPriceValue = value.GetValueOrDefault();
                this.UnitPriceValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("lotNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LotNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("disposition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Disposition { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("serialNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SerialNumber { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("bornOnDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime BornOnDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool BornOnDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> BornOnDate
        {
            get
            {
                if (this.BornOnDateValueSpecified)
                {
                    return this.BornOnDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.BornOnDateValue = value.GetValueOrDefault();
                this.BornOnDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("expirationDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.DateTime ExpirationDateValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool ExpirationDateValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<System.DateTime> ExpirationDate
        {
            get
            {
                if (this.ExpirationDateValueSpecified)
                {
                    return this.ExpirationDateValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExpirationDateValue = value.GetValueOrDefault();
                this.ExpirationDateValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("catchWeight", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double CatchWeightValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool CatchWeightValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> CatchWeight
        {
            get
            {
                if (this.CatchWeightValueSpecified)
                {
                    return this.CatchWeightValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.CatchWeightValue = value.GetValueOrDefault();
                this.CatchWeightValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("damaged", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DamagedValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DamagedValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> Damaged
        {
            get
            {
                if (this.DamagedValueSpecified)
                {
                    return this.DamagedValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DamagedValue = value.GetValueOrDefault();
                this.DamagedValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("damagedQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DamagedQuantityValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool DamagedQuantityValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> DamagedQuantity
        {
            get
            {
                if (this.DamagedQuantityValueSpecified)
                {
                    return this.DamagedQuantityValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.DamagedQuantityValue = value.GetValueOrDefault();
                this.DamagedQuantityValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _createInventory = true;
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        [System.Xml.Serialization.XmlElementAttribute("createInventory", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CreateInventory
        {
            get
            {
                return _createInventory;
            }
            set
            {
                _createInventory = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _createPo = false;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("createPO", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CreatePo
        {
            get
            {
                return _createPo;
            }
            set
            {
                _createPo = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private bool _createItem = false;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("createItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CreateItem
        {
            get
            {
                return _createItem;
            }
            set
            {
                _createItem = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("otherReferenceNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OtherReferenceNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("parentNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ParentNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("oldItemNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OldItemNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customAttribute3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomAttribute3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryCondition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryCondition { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute1 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute2 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute3 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute4 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute5 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute6", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute6 { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("inventoryAttribute7", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string InventoryAttribute7 { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Types.ChannelFieldType> _channels;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("channels", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("channel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<Types.ChannelFieldType> Channels
        {
            get
            {
                return _channels;
            }
            private set
            {
                _channels = value;
            }
        }
        
        /// <summary>
        /// </summary>
        public ReceiptLineType()
        {
            this._channels = new System.Collections.ObjectModel.Collection<Types.ChannelFieldType>();
        }
    }
}
