//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.954.0
namespace Storage
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StorageCollection", Namespace="http://integration.deposco.com/storage")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("storages", Namespace="http://integration.deposco.com/storage")]
    public partial class StorageCollection
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<StorageType> _storage;
        
        [System.Xml.Serialization.XmlElementAttribute("storage", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<StorageType> Storage
        {
            get
            {
                return _storage;
            }
            private set
            {
                _storage = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StorageSpecified
        {
            get
            {
                return (this.Storage.Count != 0);
            }
        }
        
        /// <summary>
        /// </summary>
        public StorageCollection()
        {
            this._storage = new System.Collections.ObjectModel.Collection<StorageType>();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.954.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StorageType", Namespace="http://integration.deposco.com/storage")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StorageType
    {
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("businessUnit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BusinessUnit { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("minimum", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MinimumValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MinimumValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Minimum
        {
            get
            {
                if (this.MinimumValueSpecified)
                {
                    return this.MinimumValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MinimumValue = value.GetValueOrDefault();
                this.MinimumValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("maximum", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int MaximumValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MaximumValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Maximum
        {
            get
            {
                if (this.MaximumValueSpecified)
                {
                    return this.MaximumValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MaximumValue = value.GetValueOrDefault();
                this.MaximumValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("minimumPick", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MinimumPickValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MinimumPickValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> MinimumPick
        {
            get
            {
                if (this.MinimumPickValueSpecified)
                {
                    return this.MinimumPickValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MinimumPickValue = value.GetValueOrDefault();
                this.MinimumPickValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("maximumPick", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double MaximumPickValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool MaximumPickValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> MaximumPick
        {
            get
            {
                if (this.MaximumPickValueSpecified)
                {
                    return this.MaximumPickValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.MaximumPickValue = value.GetValueOrDefault();
                this.MaximumPickValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("rating", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RatingValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool RatingValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> Rating
        {
            get
            {
                if (this.RatingValueSpecified)
                {
                    return this.RatingValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RatingValue = value.GetValueOrDefault();
                this.RatingValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlElementAttribute("opportunisticCountThreshold", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int OpportunisticCountThresholdValue { get; set; }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool OpportunisticCountThresholdValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<int> OpportunisticCountThreshold
        {
            get
            {
                if (this.OpportunisticCountThresholdValueSpecified)
                {
                    return this.OpportunisticCountThresholdValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OpportunisticCountThresholdValue = value.GetValueOrDefault();
                this.OpportunisticCountThresholdValueSpecified = value.HasValue;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute("minPickPack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pack.PackType MinPickPack { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("location", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Location { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("facilityNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FacilityNumber { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pack", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Pack.PackType Pack { get; set; }
    }
}
